### ISSUE TITLE
Use can-observation-recorder

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-connect-feathers#107]
Right now, the following warning is shown when using `Session.current`:

```
can-observation: Call add() on can-observation-recorder.
```

This line needs to be updated to use [can-observation-recorder](https://canjs.com/doc/can-observation-recorder.html): https://github.com/canjs/can-connect-feathers/blob/1d486cf507d5b93abe9091f512e2eab06ff2908e/session/session.js#L30

**Comment by cherifGsoul** [comment]
It is already fixed! 
https://github.com/canjs/can-connect-feathers/blob/0e90f1177e2ca262968bb166d34f5afa1b62f853/session/session.js#L31
