### ISSUE TITLE
Work out how to get login/logout events working securely in Feathers

### ISSUE THREAD

**Issue by marshallswain** [canjs/can-connect-feathers#21]
We can take advantage of the realtime socket events to handle sessions.  We don't want to broadcast the event to everybody in some apps, so we need to be able to secure it.

- [ ] Get login events working
- [ ] Secure them to only the current socket connection.  Or maybe even send them to the same user, so you could send notifications if they've logged in at another location.

**Comment by marshallswain** [comment]
For initial login, securing the login/logout events to the current socket connection is problematic.  If we consider that we have two pages: 

1. the main app page
2. the OAuth popup -> Success redirect page.

Before we authenticate the user, we don't have a method of marking the socket connections as belonging to the user.  So when we get successful auth on the "success redirect" page, we can't target the main app page because its socket is still anonymous.

**Comment by marshallswain** [comment]
We might be able to make this happen if we setup a way of authenticating anonymous users.  

1. On first visit, the client calls authenticate with no params.
1. The server:
  - creates a unique identifier for the unauthenticated user
  - Encodes it in a token
  - Sends it back to the client
1. The client stores it in the `feathers-jwt` cookie
1. The user opens the login with GitHub button & the Github auth popup opens
1. User successfully authenticates with GitHub & is redirected to the success page.
  - There's a problem here, because this will overwrite our token in the cookie.
1.

**Comment by ekryski** [comment]
@marshallswain can you not just:

1. pop open window
2. do the oauth dance
3. callback to parent window with token parsed from either cookie or querystring
4. authenticate the socket in the parent window with the token

You shouldn't have to try and notify the socket from server to client that they should be authenticated.

**Comment by marshallswain** [comment]
@ekryski That's what I was originally looking at doing, but I couldn't figure out how to get a reference to the parent window again after all of the redirects.

**Comment by ekryski** [comment]
Did you look at how Auth0 does it in their lock repo?

**Comment by marshallswain** [comment]
Nope.  Good idea.

**Comment by marshallswain** [comment]
There's a potential CSRF-related security concern with trusting the cookie, but I believe the likelihood of being able to pull it off is close to impossible as long as XSS attacks are properly avoided.  The perpetrator, at domain `attacker.com` would have to open a socket connection to the API server *after* the anonymous user token has been created.  This would then allow the socket connection from `attacker.com` to receive the new auth information.

But really, if there's an XSS issue on the page, why not just skim the token from localStorage or the cookie.

**Comment by marshallswain** [comment]
Closing this for now.  This might be a priority in the future, but I have the OAuth popups working, now, without this.
