### ISSUE TITLE
Generate the README.md with bit-docs

### ISSUE THREAD

**Issue by marshallswain** [canjs/can-connect-feathers#32]
I want to generate can-connect-feathers README.md from the docs in the 2.0 branch.  I know I need an apis.json like this: https://github.com/canjs/can-define/blob/master/docs/apis.json

What else needs to happen?

cc: @matthewp, @justinbmeyer

**Comment by matthewp** [comment]
look at the package.json as well, there's a bit-docs section you need in yours. Also make sure you do `mkdir doc` because the generator will not make it for you and you'll get a weird error.
