### ISSUE TITLE
ecosystem

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-connect-feathers#41]
hi @marshallswain

great work for that module!
would be very nice to have this module in the ecosystem of canjs

**Comment by marshallswain** [comment]
Depends on https://github.com/canjs/can-connect-feathers/issues/36

**Comment by marshallswain** [comment]
There's a bug in Safari such that when the rest of the CanJS tests run, the can-connect-feathers tests don't run.  Need to comment out modules in the CanJS tests and figure out which is the offender.

**Comment by marshallswain** [comment]
It's now in the canjs.com ecosystem page.
