### ISSUE TITLE
IE10 Support?

### ISSUE THREAD

**Issue by marshallswain** [canjs/can-connect-feathers#65]
Getting the following error when using IE10:

![screen shot 2017-03-08 at 5 54 03 pm](https://cloud.githubusercontent.com/assets/128857/23731009/404b3af2-0428-11e7-8ee0-d54c90632c69.jpg)

I've tried loading shims from `core-js`, but the above error is still present.  Check out the ie10 branch to debug.

![screen shot 2017-03-08 at 5 54 25 pm](https://cloud.githubusercontent.com/assets/128857/23731070/8c29a1e8-0428-11e7-83f2-925d14b55cbd.jpg)

**Comment by marshallswain** [comment]
Maybe this is the solution: http://stackoverflow.com/questions/13975922/script438-object-doesnt-support-property-or-method-ie

**Comment by christopherjbaker** [comment]
`Object.setPrototypeOf` is being used by code added by babel to feathersjs/feathers-errors. `Object.setPrototypeOf` was added to IE in 11 and isn't polyfillable (for reasons I do not understand). There is a merge pull request at babel/babel#3527 that is supposed to fix it, so I am unsure why it is still an issue.

I did test modifying the compile process of feathers-errors [to enable approximate mode](https://www.npmjs.com/package/babel-plugin-transform-builtin-extend), which did make all our tests pass (though it made 2 of theirs fail, they looked fixable). The simplest fix would probably be to request that featherjs/feathers-errors enable approximate mode.

**Comment by marshallswain** [comment]
@christopherjbaker Would you mind opening an issue in the feathers-errors repo?  We have Sauce Labs tests that run in the `feathersjs/feathers-client` repo and are testing back to IE8 (I think) with the babel-polyfill, but for some reason they're not running into this same issue.

**Comment by andrejewski** [comment]
@marshallswain @christopherjbaker What should be done here (if anything)?

**Comment by marshallswain** [comment]
I don't know the status.  We need a breaking example to see if we still need a fix.

**Comment by christopherjbaker** [comment]
Haha. I was just looking into this again. The tests definitely do not pass. This is a flat out "doesn't work in ie10", so it seems odd that we don't have users complaining (or do we?). I was able to make them pass by modifying the build process for feathers-errors (though that broke the feathers-erros tests). But the feathers-errors tests pass without the changes, so I am trying to see if the tests are hitting the breaking piece of code.

**Comment by christopherjbaker** [comment]
Alright. The erroring code is not running in the feathers-client browser tests. I was able to add a test that recreates it. I don't think it can be fixed on our end, though.

**Comment by marshallswain** [comment]
@christopherjbaker would you mind creating a PR for the `feathers-errors` repo with the failing test.  Either @daffl or I will get to it.  Please also mark this issue as dependent on that PR.

**Comment by christopherjbaker** [comment]
Done. dependent on the fix for feathersjs/feathers-client#164
(is there an official way to mark a dependency?)

**Comment by christopherjbaker** [comment]
It looks like we have a fix at feathersjs/feathers-errors#73. I will update my local copy and test.
