### ISSUE TITLE
this produces a wrong request to feathers-api

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-connect-feathers#73]
```
Error: Timeout of 5000ms exceeded calling http://localhost:3030/users::find
    at Timeout.<anonymous> (file:/home/frank/artist/node_modules/feathers-socket-commons/lib/client.js:89:25)
```
the ::find shouldnt be there

**Comment by marshallswain** [comment]
@frank-dspeed I think this might be an issue with steal-socket.io, as well.  Can you check?

**Comment by frank-dspeed** [comment]
it is i updated the other issue https://github.com/stealjs/steal-socket.io/issues/27

**Comment by marshallswain** [comment]
Ok.  Thanks for verifying.

**Comment by frank-dspeed** [comment]
oh no sorry the find was a result of the usage of getList({}) as i droped {} it worked

**Comment by frank-dspeed** [comment]
i am not sure if that is a bug i think the error results from the empty object as option and it expects something diffrent but getList() worked

**Comment by frank-dspeed** [comment]
@marshallswain this can be closed the issue was really wrong usage from me i used the socket.io connection then i used as service('http://url.com/users') naming this 'users' did the trick

**Comment by marshallswain** [comment]
Thanks!
