### ISSUE TITLE
Behaviour Hooks not calling super()

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/can-connect-feathers#76]
None of the hooks on either behaviour call the super equivalent on tho previous behaviour. I believe each should have `baseConnect.<hook>.apply(this, arguments);`, or am I mistaken?

**Comment by roemhildtg** [comment]
Yep, this appears to be a bug. It prevents the other behaviors from working.

**Comment by frank-dspeed** [comment]
@justinbmeyer please review and merge if its good looking

**Comment by chasenlehara** [comment]
Fixed by https://github.com/canjs/can-connect-feathers/pull/103 and released in [4.0.1](https://github.com/canjs/can-connect-feathers/releases/tag/v4.0.1)
